language: python
sudo: required
dist: xenial
cache: false
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest-cov
# command to install dependencies
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda -c conda-forge
  - conda env create -n imageprep -f environment.yaml
  - conda list -n imageprep
  - source activate imageprep
  - python --version
  - pip install --user -r requirements.txt -vv
  - pip install .

# command to run tests
script:
  - python -m pytest --cov-report term-missing --cov=./
  - rm *.txt

after_success:
  - codecov # submit coverage
